blueprint:
  name: ZHA - TRADFRI E1743 on/off + dim up/dim down remote
  author: marc825
  domain: automation
  input:
    remote:
      name: Remote
      description: The remote that will control the shades
      selector:
        device:
          integration: zha
          manufacturer: IKEA of Sweden
          model: TRADFRI on/off remote
          multiple: false
    on_button_short_press:
      name: On Button short press
      description: Action to run on Short Press
      default: []
      selector:
        action: {}
    on_button_long_press:
      name: On Button long press
      description: Action to run on Short Press
      default: []
      selector:
        action: {}
    off_button_short_press:
      name: Off Button short press
      description: Action to run on Short Press
      default: []
      selector:
        action: {}
    off_button_long_press:
      name: Off Button long press
      description: Action to run on Short Press
      default: []
      selector:
        action: {}
variables:
  on_button_short_press_command:
  - 'on'
  on_button_long_press_trigger_action:
  - '[<MoveMode.Up: 0>, 83]'
  off_button_short_press_command:
  - 'toggle'
  off_button_long_press_trigger_action:
  - '[<MoveMode.Down: 1>, 83, <OptionsMask: 0>, <Options: 0>]'
mode: restart
trigger:
- platform: event
  event_type: zha_event
  event_data:
    device_id: !input "remote"
action:
- variables:
    command: "{{ trigger.event.data.command }}"
    trigger_action: "{{ trigger.event.data.args }}"
- choose:
# On
  - conditions:
    - "{{ command | string in on_button_short_press_command }}"
    sequence: !input "on_button_short_press"
  - conditions: 
    - "{{ trigger_action | string in on_button_long_press_trigger_action }}"
    sequence: !input "on_button_long_press"
## Off    
  - conditions:
    - "{{ command | string in off_button_short_press_command }}"
    sequence: !input "off_button_short_press"
  - conditions: 
    - "{{ trigger_action | string in off_button_long_press_trigger_action }}"
    sequence: !input "off_button_long_press"