blueprint:
  name: Sun Elevation to Brightness
  description: Adjust brightness of lights based on the current sun elevation. If
    force debug is enabled, you need to execute this automation manually or let Home
    Assitant restart before the change take effect.
  domain: automation
  input:
    section_general:
      name: "General Settings"
      icon: "mdi:lightbulb"
      description: "Options for the general settings"
      input:
        input_number_value:
          name: Command Output Number Helper
          description: Output for Command events of Device
          default: []
          selector:
            entity:
              domain:
              - input_number
              multiple: false
        input_number_value_pct:
          name: Command Output Percentage Number Helper
          description: Output for Command events of Device
          default: []
          selector:
            entity:
              domain:
              - input_number
              multiple: false
        debounce_update:
          name: Debounce Brightness Update
          description: Time (in seconds) to wait before updating the brightness again
          default: 30
          selector:
            number:
              min: 15
              max: 300
              unit_of_measurement: 's'
              mode: slider
              step: 15
  
    section_brightness:
      name: "Sun Brightness Settings"
      icon: "mdi:brightness-5"
      description: "Options for the sun brightness"
      input:
        max_brightness:
          name: Maximum brightness
          description: Brightness to set as the maximum brightness (0-255)
          default: 255
          selector:
            number:
              min: 2.0
              max: 255.0
              mode: slider
              step: 1.0
        min_brightness:
          name: Minimum brightness
          description: Brightness to set as the minimum brightness (0-255)
          default: 1
          selector:
            number:
              min: 1.0
              max: 254.0
              mode: slider
              step: 1.0
    section_sun:
      name: "Sun Elevation Settings"
      icon: "mdi:sun-clock"
      description: "Options for the sun elevation"
      input:
        start_dim_up_rising:
          name: Elevation of the sun to start brighten the light when the sun is rising
          default: 0
          selector:
            number:
              min: -35.0
              max: 25.0
              mode: slider
              step: 0.5
        max_brightness_elevation:
          name: Elevation of the Sun at which max Brightness is applied
          default: 45
          selector:
            number:
              min: 30.0
              max: 90.0
              mode: slider
              step: 0.5
        end_dim_down_setting:
          name: Elevation of the sun to start dim the light when the sun is setting
          default: -10
          selector:
            number:
              min: -35.0
              max: 25.0
              mode: slider
              step: 0.5
mode: single
max_exceeded: silent
variables:
  debounce_update: !input 'debounce_update'
  start_setting: !input 'max_brightness_elevation'
  start_rising: !input 'start_dim_up_rising'
  end_setting: !input 'end_dim_down_setting'
  end_rising: !input 'max_brightness_elevation'
  rising: '{{ state_attr(''sun.sun'', ''rising'') }}'
  max_brightness: !input 'max_brightness'
  min_brightness: !input 'min_brightness'
  max_elevation: '{% if rising %}{{end_rising|float}}{% else %}{{start_setting|float}}{%
    endif %}'
  min_elevation: '{% if rising %}{{start_rising|float}}{% else %}{{end_setting|float}}{%
    endif %}'
  elevation: '{{ state_attr(''sun.sun'', ''elevation'') }}'
  brightness_range: '{{ max_brightness|float - min_brightness|float }}'
  delta_to_min: '{{ elevation - min_elevation }}'
  elevation_range: '{{ max_elevation - min_elevation }}'
  full_percent: |-
      {% if delta_to_min / elevation_range < 0 %}
      0
      {% elif delta_to_min / elevation_range > 1 %}
      1
      {% else %}
      {{ delta_to_min / elevation_range }}
      {% endif %}
  brightness: >-
    {% set value = (full_percent|float * brightness_range|float + min_brightness|float) | round(0) %}
    {% if value < 1 %}
    1
    {% elif value > 255 %}
    255
    {% else %}
    {{ value|int }}
    {% endif %}
  brightness_pct: '{{ (brightness / 2.55)|round(1) }}'
trigger:
- platform: state
  entity_id: sun.sun
  attribute: elevation
- platform: event
  event_type: call_service
  event_data:
    domain: light
    service: turn_on
- platform: homeassistant
  event: start
action:
- choose:
  - conditions:
    - condition: template
      value_template: "{{ input_number_value not in [none, '', []] }}"
    sequence:
      - service: input_number.set_value
        data:
          entity_id: !input input_number_value
          value: '{{ brightness }}'
- choose:
  - conditions:
    - condition: template
      value_template: "{{ input_number_value_pct not in [none, '', []] }}"
    sequence:
      - service: input_number.set_value
        data:
          entity_id: !input input_number_value_pct
          value: '{{ brightness_pct }}'
- delay: '{{ debounce_update }}'