blueprint:
  name: ZHA - TRADFRI E1743 on/off + dim up/dim down remote
  author: marc825
  domain: automation
  input:
    remote:
      name: Remote
      description: The remote that will control the shades
      selector:
        device:
          integration: zha
          manufacturer: IKEA of Sweden
          model: TRADFRI on/off remote
          multiple: false
    on_button_short_press:
      name: On Button short press
      description: Action to run on Short Press
      default: []
      selector:
        action: {}
    on_button_long_press:
      name: On Button long press
      description: Action to run on Short Press
      default: []
      selector:
        action: {}
    off_button_short_press:
      name: Off Button short press
      description: Action to run on Short Press
      default: []
      selector:
        action: {}
    off_button_long_press:
      name: Off Button long press
      description: Action to run on Short Press
      default: []
      selector:
        action: {}
mode: restart
trigger:
- platform: event
  event_type: zha_event
  event_data:
    device_id: !input "remote"
action:
- variables:
    command: "{{ trigger.event.data.command }}"
- choose:
  - conditions:
    - "{{ command == 'up_open' }}"
    sequence: !input "open_button_short_press"
  - conditions:
    - "{{ command == 'down_close' }}"
    sequence: !input "close_button_short_press"
