blueprint:
  name: Own Blueprint GH - ZHA - Light IKEA SYMFONISK remote Hook
  description: 'Steuert einen Boolean an um einer Automatisierung mitzuteilen dass der Symfonisk Sound Controller nicht mehr gedreht wird

    '
  domain: automation
  input:
    remote:
      name: Remote
      description: IKEA remote to use
      selector:
        device:
          integration: zha
          manufacturer: IKEA of Sweden
          model: SYMFONISK Sound Controller
          multiple: false
#    debounce_delay:
#      name: (Optional) Helper - Debounce delay
#      description: Delay used for debouncing RAW controller events, by default set
#        to 0. A value of 0 disables the debouncing feature. Increase this value if
#        you notice custom actions or linked Hooks running multiple times when interacting
#        with the device. When the controller needs to be debounced, usually a value
#        of 100 is enough to remove all duplicate events.
#      default: 0
#      selector:
#        number:
#          min: 0.0
#          max: 1000.0
#          unit_of_measurement: milliseconds
#         mode: box
#          step: 10.0
    input_speicher:
      name: Boolean Speicher
      default: []
      selector:
        entity:
          multiple: false
          filter:
            - domain: input_boolean
variables:
  rotate_clockwise:
  - '[<MoveMode.Up: 0>, 195, <OptionsMask: 0>, <Options: 0>]'
  rotate_anticlockwise:
  - '[<MoveMode.Down: 1>, 195, <OptionsMask: 0>, <Options: 0>]'
mode: single
max_exceeded: silent
trigger:
- platform: event
  event_type: zha_event
  event_data:
    device_id: !input remote
    command: stop
- platform: event
  event_type: zha_event
  event_data:
    device_id: !input remote
    command: move
action:
- variables:
    command: "{{ trigger.event.data.command }}"
    trigger_action: "{{ trigger.event.data.args }}"
- choose:
  - conditions:
    - "{{ command == 'stop' }}"
    sequence:
    - event: ahb_controller_event
      event_data:
        controller: !input remote
        action: stop
    - service: homeassistant.turn_on
      data: {}
      target:
        entity_id: input_boolean.badeecke_schrank_speicher
  - conditions: "{{ trigger_action | string in rotate_clockwise }}"
    sequence:
    - event: ahb_controller_event
      event_data:
        controller: !input remote
        action: rotate_clockwise
  - conditions: "{{ trigger_action | string in rotate_anticlockwise }}"
    sequence:
    - event: ahb_controller_event
      event_data:
        controller: !input remote
        action: rotate_anticlockwise
# - delay:
    # milliseconds: !input debounce_delay
